CREATE TABLE IF NOT EXISTS hospital_discharges (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    hospital_service_area VARCHAR(100) NULL,
    hospital_county VARCHAR(100) NULL,
    operating_certificate_number VARCHAR(32) NULL,
    facility_id BIGINT NULL,
    facility_name VARCHAR(255) NULL,
    age_group VARCHAR(50) NULL,
    zip_code_3_digits CHAR(3) NULL,
    gender VARCHAR(32) NULL,
    race VARCHAR(100) NULL,
    ethnicity VARCHAR(100) NULL,
    length_of_stay_raw VARCHAR(32) NULL,
    length_of_stay INT UNSIGNED NULL,
    admission_type VARCHAR(100) NULL,
    patient_disposition VARCHAR(200) NULL,
    discharge_year SMALLINT UNSIGNED NULL,
    diagnosis_code VARCHAR(32) NULL,
    diagnosis_description VARCHAR(500) NULL,
    procedure_code VARCHAR(32) NULL,
    procedure_description VARCHAR(500) NULL,
    apr_drg_code INT UNSIGNED NULL,
    apr_drg_description VARCHAR(500) NULL,
    apr_mdc_code INT UNSIGNED NULL,
    apr_mdc_description VARCHAR(500) NULL,
    severity_code TINYINT UNSIGNED NULL,
    severity VARCHAR(100) NULL,
    mortality_risk VARCHAR(100) NULL,
    medical_surgical_description VARCHAR(100) NULL,
    payment_type_1 VARCHAR(100) NULL,
    payment_type_2 VARCHAR(100) NULL,
    payment_type_3 VARCHAR(100) NULL,
    birth_weight INT UNSIGNED NULL,
    emergency_indicator BOOLEAN NULL,
    total_charges DECIMAL(18, 2) NULL,
    total_costs DECIMAL(18, 2) NULL,
    source_file VARCHAR(512) NOT NULL,
    source_row_number BIGINT UNSIGNED NOT NULL,
    record_hash CHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hospital_discharges_record_hash (record_hash),
    KEY idx_hospital_discharges_facility_id (facility_id),
    KEY idx_hospital_discharges_facility_name (facility_name),
    KEY idx_hospital_discharges_age_group (age_group),
    KEY idx_hospital_discharges_discharge_year (discharge_year),
    KEY idx_hospital_discharges_diagnosis_code (diagnosis_code),
    KEY idx_hospital_discharges_severity (severity),
    KEY idx_hospital_discharges_payment_type_1 (payment_type_1)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
