<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { createUser, deleteUser, listUsers, resetUserPassword, updateUser } from '../api/client'
import { authState, logout } from '../auth'

const router=useRouter();const users=ref([]);const loading=ref(false);const error=ref('');const showCreate=ref(false)
const form=reactive({username:'',display_name:'',email:'',role:'patient',password:'',must_change_password:true})
async function load(){loading.value=true;error.value='';try{users.value=(await listUsers()).data}catch(e){error.value=e.message}finally{loading.value=false}}
async function create(){try{await createUser(form);showCreate.value=false;Object.assign(form,{username:'',display_name:'',email:'',role:'patient',password:'',must_change_password:true});await load()}catch(e){error.value=e.message}}
async function toggle(user){try{await updateUser(user.id,{is_active:!user.is_active});await load()}catch(e){error.value=e.message}}
async function roleChanged(user,event){try{await updateUser(user.id,{role:event.target.value});await load()}catch(e){error.value=e.message;await load()}}
async function reset(user){const password=window.prompt(`为 ${user.username} 设置临时密码（至少10位，包含字母和数字）`);if(!password)return;try{await resetUserPassword(user.id,password);window.alert('密码已重置')}catch(e){error.value=e.message}}
async function remove(user){if(!window.confirm(`确定删除账号“${user.username}”吗？删除后该账号将无法登录。`))return;try{await deleteUser(user.id);await load()}catch(e){error.value=e.message}}
async function signOut(){await logout();router.replace('/login')}
onMounted(load)
</script>
<template><main class="admin"><header><div><button class="back" @click="router.push('/overview')">← 返回工作台</button><h1>用户账号管理</h1><p>创建账号、调整角色、禁用、删除账号和重置密码</p></div><div><span>{{authState.user?.display_name}}</span><button @click="signOut">退出</button></div></header><section class="toolbar"><strong>账号列表 <small>{{users.length}}</small></strong><button class="primary" @click="showCreate=!showCreate">{{showCreate?'取消':'创建用户'}}</button></section><form v-if="showCreate" class="create" @submit.prevent="create"><input v-model="form.username" required placeholder="用户名"><input v-model="form.display_name" required placeholder="显示名称"><input v-model="form.email" type="email" placeholder="邮箱（可选）"><select v-model="form.role"><option value="patient">患者用户</option><option value="doctor">医生用户</option><option value="admin">运维员用户</option></select><input v-model="form.password" type="password" required placeholder="初始密码（至少10位，含字母数字）"><button class="primary">确认创建</button></form><p v-if="error" class="error">{{error}}</p><section class="card"><table><thead><tr><th>用户</th><th>角色</th><th>邮箱</th><th>状态</th><th>最近登录</th><th>操作</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td><strong>{{user.display_name||user.username}}</strong><small>@{{user.username}}</small></td><td><select :value="user.role" :disabled="user.id===authState.user?.id" @change="roleChanged(user,$event)"><option value="patient">患者</option><option value="doctor">医生</option><option value="admin">运维员</option></select></td><td>{{user.email||'—'}}</td><td><em :class="{off:!user.is_active}">{{user.is_active?'正常':'已禁用'}}</em></td><td>{{user.last_login_at?.replace('T',' ')||'尚未登录'}}</td><td><button @click="reset(user)">重置密码</button><button :disabled="user.id===authState.user?.id" @click="toggle(user)">{{user.is_active?'禁用':'启用'}}</button><button class="danger-button" :disabled="user.id===authState.user?.id" @click="remove(user)">删除</button></td></tr></tbody></table><div v-if="loading" class="loading">正在加载…</div></section></main></template>
<style scoped>.admin{min-height:100vh;padding:34px 5vw;background:#f3f6f6;color:#2b3d3c;font-family:"Segoe UI","Microsoft YaHei",sans-serif}header,.toolbar{display:flex;justify-content:space-between;align-items:center}header h1{margin:12px 0 5px;font-size:27px}header p{color:#84918f;font-size:12px}header>div:last-child{display:flex;gap:12px;align-items:center;font-size:12px}button{padding:7px 11px;border:1px solid #d6e0df;border-radius:7px;background:#fff;color:#42605d;cursor:pointer}.back{padding:0;border:0;background:transparent;color:#258078}.toolbar{margin:30px 0 12px}.toolbar small{margin-left:5px;color:#238279}.primary{color:#fff;background:#176f6a;border-color:#176f6a}.create{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:13px;padding:16px;background:#fff;border:1px solid #dfe7e6;border-radius:10px}.create input,.create select{height:38px;padding:0 10px;border:1px solid #d9e1e0;border-radius:7px}.error{margin:10px 0;padding:10px;color:#a45149;background:#fff0ee;border-radius:7px;font-size:11px}.card{position:relative;overflow:auto;background:#fff;border:1px solid #e0e7e6;border-radius:12px}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{padding:14px;text-align:left;border-bottom:1px solid #edf0f0;font-size:11px}th{color:#85918f;background:#f8fafa;font-weight:500}td strong,td small{display:block}td small{margin-top:3px;color:#9aa5a3}td select{padding:5px;border:1px solid #dde4e3;border-radius:6px}td em{padding:4px 7px;color:#16796f;background:#e8f5f2;border-radius:5px;font-style:normal}td em.off{color:#9c5c56;background:#faeeee}td button{margin-right:5px;font-size:10px}button:disabled{opacity:.4;cursor:not-allowed}.loading{padding:25px;text-align:center;color:#899593}@media(max-width:800px){.create{grid-template-columns:1fr}.admin{padding:20px}header>div:last-child{display:none}}</style>
