<script setup>
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { adminHealth, auditLogs } from '../api/client'
const router=useRouter();const health=ref({});const logs=ref([]);const error=ref('')
async function load(){error.value='';try{const [h,l]=await Promise.all([adminHealth(),auditLogs()]);health.value=h.data;logs.value=l.data}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><main class="system"><button class="back" @click="router.push('/overview')">← 返回工作台</button><header><div><h1>系统状态与审计</h1><p>查看服务依赖、功能开关和安全操作记录</p></div><button @click="load">刷新</button></header><p v-if="error" class="error">{{error}}</p><section class="grid"><article><span>服务状态</span><strong :class="health.status">{{health.status==='ok'?'正常':'降级'}}</strong></article><article><span>SQL Server</span><strong>{{health.database?.connected?'已连接':'连接异常'}}</strong><small>{{health.database?.database||''}}</small></article><article><span>AI 模型</span><strong>{{health.llm?.configured?'已配置':'未配置'}}</strong><small>{{health.llm?.model}}</small></article><article><span>Python</span><strong>{{health.runtime?.python||'—'}}</strong></article></section><section class="panel"><h2>功能开关</h2><div class="flags"><span v-for="(value,key) in health.features" :key="key"><b>{{key}}</b><em>{{String(value)}}</em></span></div></section><section class="panel"><h2>安全审计记录</h2><div class="table"><table><thead><tr><th>时间</th><th>用户</th><th>动作</th><th>详情</th><th>IP</th></tr></thead><tbody><tr v-for="log in logs" :key="log.id"><td>{{log.created_at?.replace('T',' ')}}</td><td>{{log.username||'匿名'}}</td><td>{{log.action}}</td><td>{{log.detail||'—'}}</td><td>{{log.ip_address||'—'}}</td></tr></tbody></table></div></section></main></template>
<style scoped>.system{min-height:100vh;padding:34px 5vw;background:#f3f6f6;color:#2b3d3c;font-family:"Segoe UI","Microsoft YaHei",sans-serif}.back{padding:0;border:0;background:transparent;color:#258078}header{display:flex;align-items:end;justify-content:space-between;margin:15px 0 25px}h1{font-size:27px}header p{margin-top:6px;color:#879390;font-size:12px}button{padding:8px 12px;border:1px solid #d5dfde;border-radius:7px;background:#fff;color:#37645f;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.grid article,.panel{padding:19px;background:#fff;border:1px solid #dfe7e6;border-radius:11px}.grid span,.grid small{display:block;color:#8c9896;font-size:10px}.grid strong{display:block;margin:8px 0 3px;font-size:17px}.grid strong.ok{color:#167b71}.panel{margin-top:13px}.panel h2{margin-bottom:14px;font-size:14px}.flags{display:flex;gap:9px;flex-wrap:wrap}.flags span{padding:8px 10px;background:#f3f7f6;border-radius:6px;font-size:10px}.flags em{margin-left:6px;color:#298279;font-style:normal}.table{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{padding:10px;border-bottom:1px solid #edf0ef;text-align:left;font-size:10px}th{color:#8c9795;font-weight:500}.error{padding:10px;color:#a45149;background:#fff0ee;border-radius:7px}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}.system{padding:20px}}</style>
