<script setup>
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { publicReports } from '../api/client'
import { logout } from '../auth'
const router=useRouter();const reports=ref([]);const selected=ref(null);const loading=ref(true);const error=ref('')
async function load(){loading.value=true;try{reports.value=(await publicReports()).data;selected.value=reports.value[0]||null}catch(e){error.value=e.message}finally{loading.value=false}}
async function signOut(){await logout();router.replace('/login')}
onMounted(load)
</script>
<template><main class="page"><header><div><button @click="router.push('/overview')">← 返回总览</button><h1>公开健康分析报告</h1><p>以下内容基于脱敏聚合数据，仅供健康科普参考</p></div><button @click="signOut">退出登录</button></header><p v-if="error" class="error">{{error}}</p><section v-if="loading" class="empty">正在加载…</section><section v-else-if="!reports.length" class="empty">暂时没有已发布的公开报告</section><section v-else class="layout"><aside><button v-for="report in reports" :key="report.id" :class="{active:selected?.id===report.id}" @click="selected=report"><strong>{{report.title}}</strong><small>发布于 {{report.published_at?.replace('T',' ')}}</small></button></aside><article><h2>{{selected.title}}</h2><p class="notice">公开聚合数据 · 不含个人病历 · 不构成诊断或治疗建议</p><pre>{{selected.content}}</pre></article></section></main></template>
<style scoped>.page{min-height:100vh;padding:34px 6vw;background:#f3f6f6;color:#2b3d3c;font-family:"Segoe UI","Microsoft YaHei",sans-serif}header{display:flex;align-items:start;justify-content:space-between;margin-bottom:25px}button{padding:7px 10px;border:1px solid #d6e0df;border-radius:7px;background:#fff;color:#34736d;cursor:pointer}header div>button{padding:0;border:0;background:transparent}h1{margin:14px 0 5px;font-size:27px}header p{color:#899592;font-size:12px}.layout{display:grid;grid-template-columns:280px 1fr;gap:14px}aside,article,.empty{padding:18px;background:#fff;border:1px solid #dfe7e6;border-radius:12px}aside{display:flex;flex-direction:column;gap:7px;align-self:start}aside button{text-align:left;border-color:transparent;background:#f6f9f8}aside button.active{border-color:#b6d8d3;background:#ebf6f4}aside strong,aside small{display:block}aside small{margin-top:5px;color:#8e9997;font-size:9px}article{padding:28px}article h2{font-size:20px}.notice{margin:10px 0 18px;padding:9px;color:#3e7771;background:#edf7f5;border-radius:7px;font-size:10px}pre{font:12px/1.85 ui-monospace,Consolas,"Microsoft YaHei",monospace;white-space:pre-wrap;word-break:break-word}.empty{text-align:center;color:#879390}.error{padding:10px;color:#a45149;background:#fff0ee;border-radius:7px}@media(max-width:760px){.page{padding:20px}.layout{grid-template-columns:1fr}header>button{display:none}}</style>
